### ISSUE TITLE
MongoDB will exit in 7node example

### ISSUE THREAD

**Issue by Antilochus** [blk-io/epirus-free#13]
When I try to connect Epirus to Quorum 7 Node Example, MongoDB will always exit.

It seems that '--smallfiles' has been removed since mongo v4.2. So I think if you use mongo:latest, this command-line option should be also removed in docker-compose.yml file.

**Comment by AlexandrouR** [comment]
@Antilochus good spot, I will submit a PR.

**Comment by antonydenyer** [comment]
@AlexandrouR has this been fixed now?

**Comment by AlexandrouR** [comment]
@antonydenyer yes
