### ISSUE TITLE
"block must not be null" returned by the API container

### ISSUE THREAD

**Issue by ionionascu** [blk-io/epirus-free#14]
I am trying to get Epirus Free to load data from an Ethereum network running in another Docker Compose network and I get an error from the API container.

The Ethereum network runs geth with Proof-of-Authority:

```
instance: Geth/v1.9.3-unstable-396f1dd8-20190827/linux-amd64/go1.12.9
coinbase: 0x4eaac8f886c783c7877f9fa94ea29acbd891c490
at block: 634 (Mon, 09 Sep 2019 16:41:22 BST)
 modules: eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0
```

and after I start Epirus Free with `NODE_ENDPOINT=http://192.168.0.13:8545 docker-compose up`

I get this exception in the API container:

```
api_1      | 2019-09-10 14:16:09.319 ERROR 1 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.
api_1      | 
api_1      | java.util.concurrent.CompletionException: java.lang.IllegalStateException: java.lang.IllegalStateException: web3j.ethGetBlockByNumbe…()
api_1      |                 .block must not be null
api_1      | 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
api_1      | 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
api_1      | 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
api_1      | 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source)
api_1      | 	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
api_1      | 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
api_1      | 	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
api_1      | 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
api_1      | 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

I am not sure whether this is related, but to get past the problem with `--smallfiles` described in a separate issue (https://github.com/blk-io/epirus-free/issues/6), I changed the image for the Mongodb service to `mongo:4.0-xenial`.

Do you know what could be the problem?

**Comment by AlexandrouR** [comment]
@ionionascu is epirus running in the same network as your Ethereum network ?

**Comment by AlexandrouR** [comment]
does it work when epirus is on the same network ?

**Comment by ionionascu** [comment]
I tried both to have two docker-compose files with their own networks and using the host to link between them and modifying the epirus-free's docker-compose.yml file to just add one service with for my geth instance. Both failed either because I killed the Docker process after some time at full cpu usage or because the API instance existed with `gcl_api_1 exited with code 137`

**Comment by AlexandrouR** [comment]
what about renaming the name attribute in the network setting of epirus docker compose file to the name of the network that geth runs on

**Comment by ionionascu** [comment]
When I updated the docker-compose.yml from epirus-free to have my geth service in there, I used the same network (epirus) so I am not sure access can be a problem.

**Comment by AlexandrouR** [comment]
@ionionascu I will try to replicate

**Comment by FrNoize** [comment]
Hi,

I Have te same problem, i'm working on Ethereum and i want to explore my blockchain with Epirus-free. When i execute docker-compose up

it make a loop to get the block 0 to - 20.
![CaptureEpirus](https://user-images.githubusercontent.com/30587257/65601989-67769a00-dfa3-11e9-9c84-779cb8494a84.PNG)

And when i looked in the Database MongoDB in the table settings, i found : 
![CaptureMongo](https://user-images.githubusercontent.com/30587257/65602107-9b51bf80-dfa3-11e9-844e-c2e7629cf31a.PNG)

**Comment by AlexandrouR** [comment]
@FrNoize hey, could you re-pull the image and check if it works, please. Let me know if you get the same issue

**Comment by FrNoize** [comment]
@AlexandrouR  Yes i have the same issue.

first call :
![Capture Epirus Web](https://user-images.githubusercontent.com/30587257/65678263-479eaf00-e053-11e9-8075-473833c84bf2.PNG)

Then the range is reduced 60 by 60  : 1000 to 940 , 940 to 880 ... until 0 to -20 and make a loop

![Capture Epirus web 2](https://user-images.githubusercontent.com/30587257/65678927-75d0be80-e054-11e9-8e6f-1209b6f62a6a.PNG)

**Comment by ionionascu** [comment]
Just to confirm, I have retried with the most recent image and git repo and i still get a failure in the `api` container: `gcl_api_1 exited with code 137`

**Comment by MajdT51** [comment]
I have the same issue

**Comment by antonydenyer** [comment]
What happens when you try `eth.getBlockByNumber("0x0", true)` in the console?

**Comment by anirbansingharoy** [comment]
I am also facing the same issue. 
> What happens when you try eth.getBlockByNumber("0x0", true) in the console?
@antonydenyer Output from console 

```
{
  difficulty: "0x100000",
  extraData: "0x0000000000000000000000000000000000000000000000000000000000000000",
  gasLimit: "0x47b760",
  gasUsed: "0x0",
  hash: "0xbeea54a5caa2d298b9669c7ca3cbaa042de68731032eeda98c3b2955f6ba14a7",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0x0000000000000000000000000000000000000000",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: "0x0000000000000000",
  number: "0x0",
  parentHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: "0x21f",
  stateRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  timestamp: "0x5d5cdc87",
  totalDifficulty: "0x100000",
  transactions: [],
  transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  uncles: []
}
```

**Comment by antonydenyer** [comment]
Have you got any blocks being ingested? Also what's the digest of your docker images?

**Comment by easeev** [comment]
I have the same issue.

```
Image ID: docker-pullable://web3labs/epirus-free-api@sha256:6598d3ee47c4c422f0260e937d5d19aa0692c5dc40726fba419a53e9696698ae
```

**Comment by cedricwalter** [comment]
i also have the same issue :-(

**Comment by digulla** [comment]
Same here. Happens for every block that already exists but not for new blocks.
Looking at the JSON data returned by web3j, there is no `block` property, only `number`. See https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getblockbyhash
I have a feeling that you use slightly different parsers for existing and newly mined blocks.

**Comment by sebaraba** [comment]
Hi, sorry to hear this image created problems among our customers. I fixed all errors and updated the image on the registry. Could you guys please pull the latest image and test it again. Looking forward to hearing from you. Cheers.

**Comment by digulla** [comment]
I'm not seeing this error anymore. Thanks :-)

**Comment by sebaraba** [comment]
@ionionascu @cedricwalter @easeev @anirbansingharoy @MajdT51 @FrNoize guys, this issue should be fixed now. I will close this thread. If any other problems feel free to create a new issue please.

**Comment by sebaraba** [comment]
@ionionascu @cedricwalter @easeev @anirbansingharoy @MajdT51 @FrNoize guys, this issue should be fixed now. I will close this thread. If any other problems feel free to create a new issue please.
