### ISSUE TITLE
explorer not working

### ISSUE THREAD

**Issue by dvgoyeneche** [blk-io/epirus-free#15]
I get the following error on my browser console:

 http://192.168.2.144:3000/api//contracts 404 (Not Found)

**Comment by antonydenyer** [comment]
The api is proxied by nginx from port 80. You need http://localhost/api/contacts there's a small bug with the swagger file as it's being served up from inside docker meaning the default address is wrong.

**Comment by dvgoyeneche** [comment]
Sorry I dont understand your solution... is there a bug or it works?

**Comment by antonydenyer** [comment]
The explorer runs on port 80. You need to visit http://192.168.2.144 in your case.
