### ISSUE TITLE
Connection Failed

### ISSUE THREAD

**Issue by srdharan** [blk-io/epirus-free#17]
I have a local geth ethereum block chain running. My Mist browser and geth console are able to connect to the node.
I started the node with the following command on my Mac terminal:
./geth --datadir=./chaindata  --rpc --rpcaddr=localhost --rpcport=8545 --rpccorsdomain=“*”

I started the block chain explorer using the following command:
NODE_ENDPOINT=http://localhost:8545 docker-compose up

I have tried starting with 127.0.0.1, with localhost in the Node_endpoint, I get the same error.

I get the following error:
 java.net.ConnectException: Failed to connect to localhost/127.0.0.1:8545
blk-free-explorer | 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:225)
blk-free-explorer | 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:149)
blk-free-explorer | 	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:195)
blk-free-explorer | 	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
blk-free-explorer | 	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
blk-free-explorer | 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
blk-free-explorer | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
blk-free-explorer | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
blk-free-explorer | 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
blk-free-explorer | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
blk-free-explorer | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
blk-free-explorer | 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
blk-free-explorer | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
blk-free-explorer | 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
blk-free-explorer | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
blk-free-explorer | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
blk-free-explorer | 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
blk-free-explorer | 	at okhttp3.RealCall.execute(RealCall.java:69)
blk-free-explorer | 	at org.web3j.protocol.http.HttpService.performIO(HttpService.java:151)
blk-free-explorer | 	at org.web3j.protocol.Service.send(Service.java:34)
blk-free-explorer | 	at org.web3j.protocol.core.Request.send(Request.java:72)
blk-free-explorer | 	at io.blk.quorum.explorer.jobs.IngestNewBlocksJob.run(IngestNewBlocksJob.kt:21)
blk-free-explorer | 	at io.blk.quorum.explorer.scheduler.ScheduledTasks.newBlocksJob(ScheduledTasks.kt:24)
blk-free-explorer | 	at jdk.internal.reflect.GeneratedMethodAccessor110.invoke(Unknown Source)
blk-free-explorer | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
blk-free-explorer | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
blk-free-explorer | 	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
blk-free-explorer | 	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
blk-free-explorer | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
blk-free-explorer | 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
blk-free-explorer | 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
blk-free-explorer | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
blk-free-explorer | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
blk-free-explorer | 	at java.base/java.lang.Thread.run(Thread.java:834)
blk-free-explorer | Caused by: java.net.ConnectException: Connection refused (Connection refused)
blk-free-explorer | 	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
blk-free-explorer | 	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
blk-free-explorer | 	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
blk-free-explorer | 	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
blk-free-explorer | 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
blk-free-explorer | 	at java.base/java.net.Socket.connect(Socket.java:591)
blk-free-explorer | 	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:124)
blk-free-explorer | 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:223)
blk-free-explorer | 	... 33 common frames omitted
blk-free-explorer | 

Could you please let me know what I am doing wrong

**Comment by antonydenyer** [comment]
Hi @srdharan can you just confirm that you can `geth attach http://localhost:8545` thanks

**Comment by itskass** [comment]
Hi @antonydenyer,  same issue here when running with `NODE_ENDPOINT=http://localhost:8545`.
- `geth attach http://localhost:8545` works
- connection to metamask via the rpc also works.

@srdharan Im able to get it working by **using the remote address** instead of localhost.

**Comment by antonydenyer** [comment]
Sorry I missed the first bit. Because you're trying to call to the host machine from inside docker you need use the docker bridge network. ie `docker0` or `172.17.0.1`

`NODE_ENDPOINT=http://docker0:8545`

**Comment by whtech** [comment]
try 0.0.0.0 or your LAN ip address like 192.x.x.x or 10.x.x.x
