### ISSUE TITLE
Changing default 80 port

### ISSUE THREAD

**Issue by miji** [blk-io/epirus-free#19]
I'm trying to change the default port since I already have a service running on port 80. 

Despite I establish docker-compose config as:

nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./5xx.html:/www/error_pages/5xx.html
    ports:
      - 8080:80
    depends_on:
      - api
      - web
    networks:
      - epirus

I still get the error: 
java.util.concurrent.CompletionException: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:80

Can you help me / fix the issue?

**Comment by antonydenyer** [comment]
What have you tried? I changed the port and it works fine for me.

**Comment by miji** [comment]
Yeah, I tried. Unsuccessful thought :(

How did you do it?

**Comment by antonydenyer** [comment]
git clone then

```diff --git a/docker-compose.yml b/docker-compose.yml
index d9c00d6..3df2627 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -35,7 +35,7 @@ services:
       - ./nginx.conf:/etc/nginx/nginx.conf
       - ./5xx.html:/www/error_pages/5xx.html
     ports:
-      - 80:80
+      - 8080:80
     depends_on:
       - api
       - web
 ```
docker-compose up etc
