### ISSUE TITLE
Hyperledger Besu Authentication

### ISSUE THREAD

**Issue by ppoliani** [blk-io/epirus-free#22]
I'm running a Hyperledger Besu client and I want to connect the Epirus explorer. I'm facing an issue with making authenticated requests to the Besu node.

Besu supports two different authentication methods 

https://besu.hyperledger.org/en/stable/HowTo/Interact/APIs/Authentication/

I wonder if this explorer is able to handle any those.

**Comment by antonydenyer** [comment]
Yes, we support basic auth in the free version (NODE_ENDPOINT=https://username:pwd@xyz.com). 

We can support bearer tokens with a single sign-on solution but you'd need to use one of our paid-for offerings.
