### ISSUE TITLE
Connect to ganache on host

### ISSUE THREAD

**Issue by cburgdorf** [blk-io/epirus-free#23]
Great project!

I'm trying to connect to a ganache on the host machine.

I can run:

```
curl -X POST --header "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":1}' http://localhost:8546
```

Result:

```
{"id":1,"jsonrpc":"2.0","result":"EthereumJS TestRPC/v2.10.2/ethereum-js"}
```

Then I'm trying to run: `NODE_ENDPOINT=http://localhost:8546 docker-compose up`

That fails because it can not access the port on the host. I believe this is a docker thing but maybe there's an obvious solution that I'm missing (apart from moving ganache into a container as well).

Would be happy for any pointers.

**Comment by antonydenyer** [comment]
Because you're trying to call to the host machine from inside docker you need use the docker bridge network. ie docker0 or 172.17.0.1

NODE_ENDPOINT=http://docker0:8545

**Comment by cburgdorf** [comment]
Awesome! I can't try that write now as I'm on mobile but it looks promising! Thank you for your help!

**Comment by ammanpashasc** [comment]
I am having the same issue. I've tried docker0 and 172.17.0.1 but no luck. Ganache is running on 8545.
