### ISSUE TITLE
Docker compose issue - Version in "./docker-compose.yml" is unsupported.

### ISSUE THREAD

**Issue by stefek99** [blk-io/epirus-free#30]
Fresh install on Ubuntu

`docker-compose pull`

> WARNING: The NODE_ENDPOINT variable is not set. Defaulting to a blank string.
> ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

`docker-compose --version`
> docker-compose version 1.17.1, build unknown

`docker --version`

> Docker version 19.03.6, build 369ce74a3c

---

Because of the `19.03.6` I tried changing `version: "3.6"` to `version: "3.8"` but still the same error.

**Comment by stefek99** [comment]
### Background

I'm using Ubuntu 18.04.3 LTS as VM.

I'm using `ganache-cli` and `truffle migrations` - these are deploying a few contracts

It will be helpful for me to have a blockchain explorer running locally - I would like to see what is going on.


### Here is what I did


https://docs.docker.com/compose/compose-file/compose-versioning/

> Compose file format 3.6 
> Docker Engine release 18.02.0+


`sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs) stable"`

`sudo apt-get update`

`apt-cache madison docker-ce`

`sudo apt-get install docker-ce=18.06.3~ce~3-0~ubuntu`


https://github.com/docker/compose/releases/tag/1.20.1


```
curl -L https://github.com/docker/compose/releases/download/1.20.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
```

I'm using `1.20.1` because `1.20.0` introduced the 3.6 format. See [release notes](https://github.com/docker/compose/releases/tag/1.20.0)


`sudo /usr/local/bin/docker-compose pull`

```
[sudo] password for ms: 
WARNING: The NODE_ENDPOINT variable is not set. Defaulting to a blank string.
Pulling mongodb (mongo:latest)...
latest: Pulling from library/mongo
Digest: sha256:efc408845bc917d0b7fd97a8590e9c8d3c314f58cee651bd3030c9cf2ce9032d
Status: Image is up to date for mongo:latest
Pulling api (web3labs/epirus-free-api:latest)...
latest: Pulling from web3labs/epirus-free-api
Digest: sha256:a45455b519b84632bfe0162d0a09d2c545c2632d6c6d8c123c54b27775f4c1c4
Status: Image is up to date for web3labs/epirus-free-api:latest
Pulling web (web3labs/epirus-free-web:latest)...
latest: Pulling from web3labs/epirus-free-web
Digest: sha256:7360c7b5e8bf3cde3b7cc33b39d776d0af296d94336b6f337a36a031bb3b826b
Status: Image is up to date for web3labs/epirus-free-web:latest
Pulling ingestion (web3labs/epirus-free-ingestion:latest)...
latest: Pulling from web3labs/epirus-free-ingestion
57df1a1f1ad8: Already exists
71e126169501: Already exists
1af28a55c3f3: Already exists
a9777c2d5c29: Already exists
e85100469d1f: Already exists
4c8cb05e5e59: Already exists
3a7ac0f60ae7: Pull complete
8281c53794cf: Pull complete
902d870cd53d: Pull complete
4d00ce0f8f9f: Pull complete
Digest: sha256:b57dba2a3682721e716e61020137758cefea57834ef85c4c9ebfa2737770b6e3
Status: Downloaded newer image for web3labs/epirus-free-ingestion:latest
Pulling nginx (nginx:latest)...
latest: Pulling from library/nginx
bb79b6b2107f: Pull complete
111447d5894d: Pull complete
a95689b8e6cb: Pull complete
1a0022e444c2: Pull complete
32b7488a3833: Pull complete
Digest: sha256:ed7f815851b5299f616220a63edac69a4cc200e7f536a56e421988da82e44ed8
Status: Downloaded newer image for nginx:latest
```

`sudo NODE_ENDPOINT=http://172.16.239.1:8545 /usr/local/bin/docker-compose up`

> ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?
> If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

### OK, I need to start Docker daemon, so in a new tab

`sudo dockerd`

```
INFO[2020-10-22T14:53:43.555220524+01:00] libcontainerd: docker-containerd is still running  pid=13357
INFO[2020-10-22T14:53:43.555316899+01:00] parsed scheme: "unix"                         module=grpc
INFO[2020-10-22T14:53:43.555337994+01:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2020-10-22T14:53:43.555379183+01:00] ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/docker-containerd.sock 0  <nil>}]  module=grpc
INFO[2020-10-22T14:53:43.555401977+01:00] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2020-10-22T14:53:43.555434968+01:00] pickfirstBalancer: HandleSubConnStateChange: 0xc420197300, CONNECTING  module=grpc
WARN[2020-10-22T14:54:03.555860591+01:00] grpc: addrConn.createTransport failed to connect to {unix:///var/run/docker/containerd/docker-containerd.sock 0  <nil>}. Err :connection error: desc = "transport: error while dialing: dial unix:///var/run/docker/containerd/docker-containerd.sock: timeout". Reconnecting...  module=grpc
INFO[2020-10-22T14:54:03.556017757+01:00] pickfirstBalancer: HandleSubConnStateChange: 0xc420197300, TRANSIENT_FAILURE  module=grpc
INFO[2020-10-22T14:54:03.556128234+01:00] pickfirstBalancer: HandleSubConnStateChange: 0xc420197300, CONNECTING  module=grpc
WARN[2020-10-22T14:54:23.556518392+01:00] grpc: addrConn.createTransport failed to connect to {unix:///var/run/docker/containerd/docker-containerd.sock 0  <nil>}. Err :connection error: desc = "transport: error while dialing: dial unix:///var/run/docker/containerd/docker-containerd.sock: timeout". Reconnecting...  module=grpc
INFO[2020-10-22T14:54:23.556591980+01:00] pickfirstBalancer: HandleSubConnStateChange: 0xc420197300, TRANSIENT_FAILURE  module=grpc
INFO[2020-10-22T14:54:23.556742554+01:00] pickfirstBalancer: HandleSubConnStateChange: 0xc420197300, CONNECTING  module=grpc
WARN[2020-10-22T14:54:43.557281350+01:00] Failed to dial unix:///var/run/docker/containerd/docker-containerd.sock: grpc: the connection is closing; please retry.  module=grpc
Failed to connect to containerd: failed to dial "/var/run/docker/containerd/docker-containerd.sock": context deadline exceeded
```

### Some Google-fu

**Failed to connect to containerd: failed to dial "/var/run/docker/containerd/docker-containerd.sock": context deadline exceeded**

https://github.com/docker/for-linux/issues/517

> This is due to the version of dockerclient being too low. After uninstalling docker, install the new version of dockerclient.

I just want to have a better workflow with my Solidity code and inspect visually what the smart contract is doing, messing around with  Docker versions is low on my priority lists...

...maybe you can update the config to the latest, that would be easier for me :)

**Comment by SweeXordious** [comment]
I just tested it with `docker-compose` version: `1.27.2` And:

```
Client: Docker Engine - Community
 Azure integration  0.1.15
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:41:33 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
Which are pretty recent.
Try using the following please: 
```
$ curl -L https://github.com/docker/compose/releases/download/1.27.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
```
And let us know the result.

**Comment by stefek99** [comment]
### Cannot reproduce 😇

Somehow, automagically, it got resolved. Maybe I just restarted my VM? Hard to tell..

Instead I'm getting another set of errors, please see this: https://github.com/blk-io/epirus-free/issues/31

### Simple step-by-step instructions

A collegue in the off-shore development team was super kind to support me with Docker - all the credit goes to them. I'm just copy-paste the essence so in case I need do it again from scratch it will be much easier...

## 1. Docker

`sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common`

`curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -`

`sudo apt-key fingerprint 0EBFCD88`

`sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"`

`sudo apt-get update`

`sudo apt-get install docker-ce docker-ce-cli containerd.io`

> You need to add user into docker group. by 'sudo gpasswd -a _________ docker' (_________  is your user name) 
> Used to solve the error message of " docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?."

`sudo systemctl restart docker.service`

> Test whether docker is installed and started correctly

`sudo docker run hello-world`


## 2. Docker compose

`sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose`

`sudo chmod +x /usr/local/bin/docker-compose`


## Node (NVM)

`curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash`

`export NVM_DIR="$HOME/.nvm"`
`[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm`
`[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion`

`nvm install --lts`

`npm install -g ganache-cli`

`ganache-cli --mnemonic "________ ______ _____"`

Install Metamask: https://metamask.io

Import the mnemonic that `ganache-cli` is using so that your account will get ETH.

### Epirus

`git clone https://github.com/blk-io/epirus-free.git`

`cd epirus-free/`

`sudo docker-compose pull`

### IP address

`sudo apt install net-tools`

`ifconfig | grep inet`

> My local IP address: 172.16.239.1 

### 

`sudo NODE_ENDPOINT=http://172.16.239.1:8545 docker-compose up`
