### ISSUE TITLE
Something went broken after your latest updates

### ISSUE THREAD

**Issue by icinsight** [blk-io/epirus-free#6]
I got the free version up and running with your version ~Aug 10, 2019. That is my "mainnet":
http://165.22.231.61/transactions

Unfortunately the later testnet installation doesn't work. I have tried all my regular tricks.
http://68.183.204.119/transactions

I have also waited for 24 hours the chain to load. It is not a big one anyway.

Settings can be found in this site if you want to try yourself: https://secreneum.com/

![image](https://user-images.githubusercontent.com/39129866/63067015-571eca00-bee3-11e9-9ede-9e13278d68d1.png)

**Comment by whtech** [comment]
I spent lot of time on this. you can try to solve it with following steps.
1. run `docker ps`, check if there are 4 docker instance running: nginx, web, api, mongo.
2. if there are 1 or 2 missing, run ' docker ps -a ` get the dead instance id like `a12b2c3`.
3. then run `docker logs id`,(id should be the above one). you should get the log. check if there was some error, like memory, smallsize, timeout etc...

**Comment by icinsight** [comment]
Following your instructions, this seems to be the problem:

log:
mongodb_1  | Error parsing command line: unrecognised option '--smallfiles']
epirus-free_mongodb_1 exited with code 2

Mongo fails first, then something with api as well:

docker ps -a

3d7408f2e237        web3labs/epirus-free-api:latest   "/bin/sh -c 'exec ja…"   19 minutes ago      Exited (1) 53 seconds ago                            epirus-free_api_1

857831f94e3d        mongo:latest                      "mongod --smallfiles…"   19 minutes ago      Exited (2) 2 minutes ago                             epirus-free_mongodb_1

api-log has Mongo-related errors so that makes sense.

Verdict: unrecognised option '--smallfiles' => problem!

**Comment by whtech** [comment]
same here, but I solved it.
it's odd here, on my mac the latest mongo version worked, but not on ubuntu.

open the `docker-compose.yml` file, and change  `images:lastest` to  `image: mongo:4.0-xenial`

**Comment by icinsight** [comment]
Works perfect!

http://testnet-explorer.secreneum.com/

Ingesting 1500 blocks took 10 s during the startup.

Thank you!
