### ISSUE TITLE
Contract Metadata Format needed

### ISSUE THREAD

**Issue by icinsight** [blk-io/epirus-free#7]
Your explorer is wonderful and works very smoothly. I'm using it on daily basis on my private Quorum networks.

Do you have a format or template for contract metadata to be uplaoded? I'm trying to upload an ABI file that works in other settings, but here it throws an error. Can you post a link to an example metadata file? Thanks!

![image](https://user-images.githubusercontent.com/39129866/63216949-28d40100-c114-11e9-960a-f5ea24cdcaae.png)

->

![image](https://user-images.githubusercontent.com/39129866/63216969-4dc87400-c114-11e9-9ac4-be69aba8900b.png)

**Comment by whtech** [comment]
Same got 405 error. I haven't solved it yet.
This project is partial opensouced, only the docker-compose file. It's hard to add new feature for it. I plan to rewrite the api my self now.

**Comment by antonydenyer** [comment]
Hi there, we don't support contract metadata on the free version. It's available on our paid-for versions. Drop us an email hi@web3labs.com to find out more.

**Comment by icinsight** [comment]
Ok, no problem. Thanks for the response!
